# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e487af55615516d9e88e62651e3a17d69c9f4bd075186d85217cdedea81f53faace88b5c4d5a1f01abac85f9df631b909f96fc586b45adb65cee77576c710998

test:
  secret_key_base: 1af23d8e067d7e89150adfbeb3bb650db6d09bcc29bdefee8150579661cab703bf250a9e2b3bb794945f4eac0482e097f3ab3d5097ccc3d98a2cfadf15c8881d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
